const users = [
  {
    id: "user_1",
    category: 0,
    firstName: "minamba",
    lastName: "camara",
    pseudonym: "mins",
    sexe: "H",
    level: "1",
    mail: "minamba@gmail.com",
  },
  {
    id: "user_2",
    category: 0,
    firstName: "arnaud",
    lastName: "alcindor",
    pseudonym: "arn",
    sexe: "H",
    level: "1",
    mail: "arnaud@gmail.com",
  },
  {
    id: "user_3",
    category: 0,
    firstName: "marine",
    lastName: "portier",
    pseudonym: "mawin",
    sexe: "H",
    level: "1",
    mail: "marine@gmail.com",
  },
  {
    id: "user_4",
    category: 0,
    firstName: "kaba",
    lastName: "dialo",
    pseudonym: "kbz",
    sexe: "H",
    level: "1",
    mail: "kaba@gmail.com",
  },
  {
    id: "user_5",
    category: 0,
    firstName: "issa",
    lastName: "abraham",
    pseudonym: "brams",
    sexe: "H",
    level: "1",
    mail: "issa@gmail.com",
  },
  {
    id: "user_6",
    category: 0,
    firstName: "moriba",
    lastName: "diarra",
    pseudonym: "morib",
    sexe: "H",
    level: "1",
    mail: "moriba@gmail.com",
  },
  {
    id: "user_7",
    category: 0,
    firstName: "abdallah",
    lastName: "konaté",
    pseudonym: "abd",
    sexe: "H",
    level: "1",
    mail: "abdallah@gmail.com",
  },
  //   {
  //     id: "user_8",
  //     category: 0,
  //     firstName: "minamba",
  //     lastName: "camara",
  //     pseudonym: "mins",
  //     sexe: "H",
  //     level: "1",
  //     mail: "minamba@gmail.com",
  //   },
  //   {
  //     id: "user_9",
  //     category: 0,
  //     firstName: "minamba",
  //     lastName: "camara",
  //     pseudonym: "mins",
  //     sexe: "H",
  //     level: "1",
  //     mail: "minamba@gmail.com",
  //   },
];

export const list = [users];
